name: number_to_indian_words
description: Convert numbers to word formate in indian style.
version: 1.0.1
repository: https://github.com/abdulrehmank7/number-to-indian-words

environment:
  sdk: '>=2.19.2 <4.0.0'

# dependencies:


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
